spring:
  security:
      user:
        name: admin
        password: admin

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Creates or updates the database schema based on entities that already exist
      #ddl-auto: create # for first time database setup with tables
    show-sql: true # Shows the SQL queries in the logs
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: microservice
    
server:
  port: 8080
